# Generated by Django 4.1.3 on 2023-03-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lottery',
            options={'verbose_name_plural': 'Lotteries'},
        ),
        migrations.AddField(
            model_name='lottery',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
