# Generated by Django 4.1.3 on 2023-03-08 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_alter_participant_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='relation',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
