# Generated by Django 4.1.3 on 2023-03-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0007_participant_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=999)),
                ('lottery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='participants.lottery')),
            ],
        ),
    ]
